### ISSUE TITLE
Move to executablebooks?

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/github-activity#32]
Remembered to raise this when I noticed there is no changelog in your release of sphinx-book-theme 😉

**Comment by choldgraf** [comment]
ah good call

added a changelog here: https://github.com/executablebooks/sphinx-book-theme/pull/175
will move now

**Comment by chrisjsewell** [comment]
Yeh and not sure about this whole gathering PRs rather than commits? 😬 
Like, it hasn't worked for the last myst-parser and myst-nb releases because I did merges and/or rebases; commits are the record of whats changed not PRs 😉

**Comment by choldgraf** [comment]
I think grabbing commits would be cool too as a user option. I just started with PRs because that's what the non-python changelog generators I was riffing off of seemed to be doing (in particular [this ruby changelog generator](https://github.com/github-changelog-generator/github-changelog-generator)) and because I was using *tags* to categorize things. It'd be nice to make it possible for rebase commits w/ multiple changes to all be picked up (I guess the links in the changelog would all just point to the same PR)

In general there is probably a lot that can be improved in this repo. I made it as a personal tool, and started putting more time into it when others said it was useful, but I think that means it has a lot of ad-hoc design etc that is probably sub-optimal.

**Comment by chrisjsewell** [comment]
oh yeh it definitely can be helpful 👍

**Comment by consideRatio** [comment]
Ping for closure ;)

**Comment by choldgraf** [comment]
closed!
